# Generated by Django 3.2.4 on 2023-07-05 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_auto_20230705_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requisition',
            old_name='appproval_role',
            new_name='approval_role',
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 21, 6, 41, 132880)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 21, 6, 41, 131881)),
        ),
    ]
