# Generated by Django 3.2.4 on 2023-07-05 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_auto_20230705_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 21, 10, 16, 825096)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='approval_role',
            field=models.CharField(choices=[('Department Head', 'Department Head'), ('Store Executive', 'Store Executive'), ('Administration', 'Administration')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 21, 10, 16, 824094)),
        ),
    ]
