# Generated by Django 3.2.4 on 2023-07-05 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20230705_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 21, 14, 21, 650095)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='approval_role',
            field=models.CharField(choices=[('Department Head', 'Department Head'), ('Store Executive', 'Store Executive'), ('Administration', 'Administration')], default='Department Head', max_length=100),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 5, 21, 14, 21, 648096)),
        ),
    ]
