# Generated by Django 3.2.4 on 2023-07-07 04:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_auto_20230705_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisition',
            name='products',
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 10, 18, 54, 657137)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 10, 18, 54, 647647)),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_details', models.CharField(max_length=100)),
                ('brand_name', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=20)),
                ('requisition_qty', models.IntegerField()),
                ('requisition_date', models.DateField()),
                ('requisition_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.requisition')),
            ],
        ),
    ]
