# Generated by Django 3.2.4 on 2023-07-07 06:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0007_auto_20230707_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 11, 42, 29, 220545)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 11, 42, 29, 220545)),
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_role', models.CharField(choices=[('Department Head', 'Department Head'), ('Store Executive', 'Store Executive'), ('Administration', 'Administration')], max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('requisition_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.requisition')),
            ],
        ),
    ]
