# Generated by Django 3.2.4 on 2023-07-07 06:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0008_auto_20230707_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 11, 55, 24, 963838)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 11, 55, 24, 962810)),
        ),
    ]
