# Generated by Django 3.2.4 on 2023-07-07 06:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_auto_20230707_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='requisition_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.requisition'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 12, 20, 12, 614197)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 12, 20, 12, 614197)),
        ),
    ]
