# Generated by Django 3.2.4 on 2023-07-07 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_auto_20230707_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='status',
            field=models.CharField(default='PENDING', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 12, 57, 50, 403543)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 12, 57, 50, 403543)),
        ),
    ]
