# Generated by Django 3.2.4 on 2023-07-07 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_auto_20230707_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='remark',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='approval',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 13, 52, 50, 772747)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 13, 52, 50, 772747)),
        ),
    ]
