# Generated by Django 3.2.4 on 2023-07-07 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_auto_20230707_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='report',
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 21, 11, 6, 648205)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 7, 21, 11, 6, 648205)),
        ),
    ]
