# Generated by Django 3.2.4 on 2023-07-08 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0019_auto_20230707_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(default='Initialise', max_length=100),
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 12, 58, 57, 730036)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 12, 58, 57, 714410)),
        ),
    ]
