# Generated by Django 3.2.4 on 2023-07-08 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0020_auto_20230708_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='plain_text_password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 14, 54, 1, 635530)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 14, 54, 1, 635530)),
        ),
    ]
