# Generated by Django 3.2.4 on 2023-07-08 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0021_auto_20230708_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='notification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 16, 8, 24, 856459)),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 16, 8, 24, 856459)),
        ),
    ]
