# Generated by Django 3.2.4 on 2023-07-08 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0022_auto_20230708_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='trans_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 20, 33, 45, 513517)),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='requisition',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='workorder',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requisition',
            name='requisition_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 8, 20, 33, 45, 513517)),
        ),
    ]
